version: '3'

services:
  rest-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest-service
    restart: unless-stopped
    depends_on:
      - postgresql
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src:/usr/src/app/src
    environment:
      PORT: '${PORT}'
      POSTGRES_HOST: '${POSTGRES_CONTAINER_NAME}'
      POSTGRES_PORT: '${POSTGRES_PORT}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
      CRYPT_SALT: '${CRYPT_SALT}'
      JWT_SECRET_KEY: '${JWT_SECRET_KEY}'
      JWT_SECRET_REFRESH_KEY: '${JWT_SECRET_REFRESH_KEY}'
      TOKEN_EXPIRE_TIME: '${TOKEN_EXPIRE_TIME}'
      TOKEN_REFRESH_EXPIRE_TIME: '${TOKEN_REFRESH_EXPIRE_TIME}'
    networks:
      - my-app-network

  postgresql:
    build:
      context: ./PostgreSQL
      dockerfile: Dockerfile
    container_name: '${POSTGRES_CONTAINER_NAME}'
    restart: unless-stopped
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - ./PostgreSQL/data:/var/lib/postgresql/data
      - ./PostgreSQL/logs:/logs
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    networks:
      - my-app-network
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs

networks:
  my-app-network:
    name: 'my-app-network'
